### ISSUE TITLE
Buffer Overflows

### ISSUE THREAD

**Issue by DamoSWL** [dianestephens/fileserver_cpp#33]
Project: fileserver
Reported By: Weili Shi [Team Blue]

Vulnerability Type:   Format String Vulnerability causing Memory Access Violation and Buffer over-read 
Analysis Method Used: flaw finder
Exploit Description: Yes, can read memory parts that are not intended to, causing a breach in the system

Vulnerability Description:
server.cpp 537 (strcat)

`

        if ((dir = opendir("users/")) != NULL) {

          while ((ent = readdir(dir)) != NULL) {

            if(strcmp(ent->d_name, ".") != 0 && strcmp(ent->d_name, "..") != 0){

              strcat(users, ent->d_name);

              char space[2] = " "; 

              strcat(users, space);

            }

          }
`
the strcat function will copy all the characters from source string to the destination string. but if the size of destination string is smaller than the source destination string, it will cause memory overflow which makes program vulnerable. So my suggestion is that replace the strcat with strncat and copy the number of the character smaller than the size of the destination string. the modification can be like this.

`

        if ((dir = opendir("users/")) != NULL) {

          while ((ent = readdir(dir)) != NULL) {

            if(strcmp(ent->d_name, ".") != 0 && strcmp(ent->d_name, "..") != 0){

              strncat(users, ent->d_name, 256);

              char space[2] = " "; 

              strncat(users, space,2);

            }

          }
`

the program will be more robust when the strncat is applied.

**Comment by mustakimur** [comment]
@dianestephens @Sumitsahu896 can you check the bug and confirm if any of the strcat source is user input? If it is a vulnerability, please apply the patch too.

**Comment by irfanOzn** [comment]
Hi,

Thanks for the bug report. I analyzed the bug you mentioned and saw that it is not a real bug. In the 537th line, the strncat function's source is user input and may be larger than the buffer of the users array at first glance. However, the length of that array is limited to 20 on the client.cpp line 166. As a result, a username cannot be larger than 20 characters, so does the resulting file named username, which is the source string of strcat function specified as ent->d_name. 

![image](https://user-images.githubusercontent.com/76975914/112080415-57b82180-8b58-11eb-825e-9720b536e80b.png)




Another strncat function you defined that is replacing the strcat in the 539th line also does not lead to a buffer overflow vulnerability because the space[] array is not user input and has a fixed length, have a smaller length than the users array.

Thanks.

**Comment by mustakimur** [comment]
@irfanOzn @DamoSWL if the issue has been resolved, please close this issue.
